// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP satelliteTools_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// mSpecIndicesCPP
List mSpecIndicesCPP(NumericVector blue, NumericVector green, NumericVector red, NumericVector nir);
RcppExport SEXP satelliteTools_mSpecIndicesCPP(SEXP blueSEXP, SEXP greenSEXP, SEXP redSEXP, SEXP nirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type blue(blueSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type green(greenSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type red(redSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nir(nirSEXP);
    rcpp_result_gen = Rcpp::wrap(mSpecIndicesCPP(blue, green, red, nir));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"satelliteTools_rcpp_hello_world", (DL_FUNC) &satelliteTools_rcpp_hello_world, 0},
    {"satelliteTools_mSpecIndicesCPP", (DL_FUNC) &satelliteTools_mSpecIndicesCPP, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_satelliteTools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
