# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('satelliteTools_rcpp_hello_world', PACKAGE = 'satelliteTools')
}

mSpecIndicesCPP <- function(blue, green, red, nir) {
    .Call('satelliteTools_mSpecIndicesCPP', PACKAGE = 'satelliteTools', blue, green, red, nir)
}

