# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_stPCA <- function(mtrx) {
    .Call('satelliteTools_rcpp_stPCA', PACKAGE = 'satelliteTools', mtrx)
}

rcpparma_outerproduct <- function(x) {
    .Call('satelliteTools_rcpparma_outerproduct', PACKAGE = 'satelliteTools', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('satelliteTools_rcpparma_innerproduct', PACKAGE = 'satelliteTools', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('satelliteTools_rcpparma_bothproducts', PACKAGE = 'satelliteTools', x)
}

